repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: 'parsl_ephemeral_aws/templates/cloudformation/.*\.yml$'
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-private-key
    -   id: mixed-line-ending
        args: ['--fix=lf']

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-boto3, boto3-stubs]
        exclude: ^(tests/|docs/|setup.py|examples/)

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
    -   id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']

# TODO: Enable REUSE tool after adding copyright headers to all files
# -   repo: https://github.com/fsfe/reuse-tool
#     rev: v2.1.0
#     hooks:
#     -   id: reuse
#         args: ['lint']

-   repo: https://github.com/srstevenson/nb-clean
    rev: 3.0.1
    hooks:
    -   id: nb-clean
        args: ["--preserve-cell-outputs"]

-   repo: local
    hooks:
    -   id: pytest-unit
        name: pytest-unit
        entry: python3
        language: system
        pass_filenames: false
        always_run: true
        args: [-m, pytest, -m, "unit", --maxfail=5, -x, -q]

    -   id: coverage-check
        name: coverage-check
        entry: bash
        language: system
        pass_filenames: false
        always_run: true
        args: [-c, "python3 -m coverage run -m pytest -m 'unit' && python3 -m coverage report --fail-under=70"]

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.11.0
    hooks:
    -   id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 Scott Friedman and Project Contributors
