"""CurveZMQ certificate distribution (#62).

These tests use real certificates, generated by pyzmq into ``tmp_path``, rather
than fixtures with plausible-looking strings. The reason is that the defect class
here is "the worker cannot use what we shipped", and only real key material
proves otherwise -- a test that ships ``b"fake"`` and asserts ``b"fake"`` arrives
would pass against a distributor that shipped the wrong *files*.

The one behaviour these cannot cover is a live SecureString round-trip and an
instance-profile fetch; that is in ``tests/aws/test_curvezmq_e2e.py``.

SPDX-License-Identifier: Apache-2.0
SPDX-FileCopyrightText: 2025-2026 Scott Friedman and Project Contributors
"""

import base64
import json
import os
import subprocess
import sys
from contextlib import contextmanager
from unittest.mock import MagicMock

import pytest
import zmq
from botocore.exceptions import ClientError
from parsl import curvezmq

from parsl_ephemeral_provider.exceptions import (
    ProviderConfigurationError,
    ResourceCreationError,
)
from parsl_ephemeral_provider.security.curvezmq import (
    CERT_DIR_MODE,
    WORKER_CERT_FILES,
    CurveZMQCertificateDistributor,
    certificate_iam_statements,
    extract_cert_dir,
    read_worker_certificates,
)

pytestmark = pytest.mark.unit


@pytest.fixture
def cert_dir(tmp_path):
    """A real interchange certificate directory, as HTEX would create it."""
    return curvezmq.create_certificates(tmp_path / "driver")


@pytest.fixture
def distributor():
    """A distributor over a mocked SSM client, exposed as ``.ssm``."""
    session = MagicMock()
    ssm = MagicMock()
    session.client.return_value = ssm
    session.region_name = "us-east-1"
    dist = CurveZMQCertificateDistributor(session=session, provider_id="prov1234")
    dist.ssm = ssm  # test convenience; not part of the class's interface
    return dist


class TestExtractCertDir:
    """The provider learns the certificate path from the command, not the caller.

    HTEX creates the certificates in ``start()`` and only then interpolates
    ``cert_dir`` into ``launch_cmd`` (``executor.py:441`` then ``:472``), so the
    path is already in the command by the time ``submit_job`` sees it. #62
    assumed the opposite and dismissed this approach as impossible for it.
    """

    #: The real DEFAULT_LAUNCH_CMD shape, post-interpolation.
    LAUNCH_CMD = (
        "process_worker_pool.py  --max_workers_per_node=4 -a 10.0.1.5 -p 0 "
        "-c 1 -m None --poll 10 --port=54321 "
        "--cert_dir /home/u/runinfo/000/htex/certificates "
        "--logdir=/x --block_id=0 --hb_period=30"
    )

    def test_it_finds_the_path_in_a_real_launch_command(self):
        assert (
            extract_cert_dir(self.LAUNCH_CMD) == "/home/u/runinfo/000/htex/certificates"
        )

    def test_the_equals_form_is_accepted(self):
        """Not what HTEX emits today, but a custom ``launch_cmd`` may."""
        assert (
            extract_cert_dir("x --cert_dir=/a/b/certificates -y") == "/a/b/certificates"
        )

    def test_parsls_literal_None_is_not_a_path(self):
        """``encrypted=False`` formats the string "None" into the command.

        Treating that as a directory would make the provider publish
        certificates for an unencrypted run and then fail to read a directory
        named ``None``.
        """
        assert (
            extract_cert_dir(
                self.LAUNCH_CMD.replace("/home/u/runinfo/000/htex/certificates", "None")
            )
            is None
        )

    def test_a_command_without_certificates_yields_None(self):
        assert extract_cert_dir("python -c 'print(1)'") is None


class TestReadWorkerCertificates:
    """What a worker needs is a verified fact, not a guess.

    ``curvezmq.ClientContext.socket`` calls ``_load_certificate`` for both
    ``client`` and ``server``, and that helper reads the ``.key_secret`` file in
    each case -- so the server's *secret* file is required even though only its
    public half is used. Shipping ``server.key`` instead raises
    ``OSError: Invalid certificate file``.
    """

    def test_it_reads_exactly_the_two_files_a_worker_opens(self, cert_dir):
        assert sorted(read_worker_certificates(cert_dir)) == sorted(WORKER_CERT_FILES)

    def test_the_public_only_files_are_not_shipped(self, cert_dir):
        """``.key`` files are never opened by a client, so they are dead weight.

        They are also the ones it would be *safe* to ship, which is exactly why
        this is worth pinning: an implementation that shipped only these would
        look more secure and would not work.
        """
        shipped = read_worker_certificates(cert_dir)
        assert "client.key" not in shipped
        assert "server.key" not in shipped

    def test_the_content_is_the_file_bytes_base64_encoded(self, cert_dir):
        shipped = read_worker_certificates(cert_dir)
        for name in WORKER_CERT_FILES:
            with open(os.path.join(cert_dir, name), "rb") as handle:
                assert base64.b64decode(shipped[name]) == handle.read()

    def test_a_missing_directory_is_a_configuration_error(self, tmp_path):
        with pytest.raises(ProviderConfigurationError, match="does not exist"):
            read_worker_certificates(str(tmp_path / "nope"))

    def test_a_missing_certificate_names_both_required_files(self, cert_dir):
        os.remove(os.path.join(cert_dir, "server.key_secret"))
        with pytest.raises(ProviderConfigurationError) as exc:
            read_worker_certificates(cert_dir)
        # The error has to explain why the *server* secret is wanted, or the
        # reader concludes it is a bug and removes it.
        assert "server.key_secret" in str(exc.value)
        assert "public key" in str(exc.value)


class TestTheWorkerCanActuallyUseWhatIsShipped:
    """The end-to-end property, and the only one that matters for #62.

    Everything else is plumbing: if a worker that holds only the shipped bytes
    cannot complete a CurveZMQ handshake with the interchange, the feature does
    not work regardless of how the parameters are named.
    """

    @staticmethod
    def _materialise(shipped, dest):
        """Run the same decode the generated UserData runs, in a subprocess.

        A subprocess rather than an inline loop so the ``python3 -c`` body in
        ``fetch_script`` is what is under test, not a re-implementation of it.
        """
        os.makedirs(dest, mode=0o700, exist_ok=True)
        payload = os.path.join(os.path.dirname(dest), "payload.json")
        with open(payload, "w") as handle:
            json.dump(shipped, handle)
        subprocess.run(
            [
                sys.executable,
                "-c",
                f"""
import base64, json, os
with open({payload!r}) as handle:
    certs = json.load(handle)
for filename, encoded in certs.items():
    path = os.path.join({dest!r}, filename)
    with open(path, 'wb') as out:
        out.write(base64.b64decode(encoded))
    os.chmod(path, 0o600)
""",
            ],
            check=True,
        )
        os.chmod(dest, 0o700)
        return dest

    def test_a_worker_holding_only_the_shipped_files_can_build_a_socket(
        self, cert_dir, tmp_path
    ):
        worker_dir = self._materialise(
            read_worker_certificates(cert_dir),
            str(tmp_path / "worker" / "certificates"),
        )
        ctx = curvezmq.ClientContext(worker_dir)
        assert ctx.socket(zmq.DEALER) is not None

    @staticmethod
    @contextmanager
    def _channel(server_cert_dir, client_cert_dir):
        """Yield a bound server socket and a connected client socket.

        ``LINGER=0`` on both, and ``destroy(linger=0)`` on teardown, is
        load-bearing rather than tidiness: the rejected-client test below sends a
        message that is never delivered, and at ZMQ's default linger of -1
        ``close()`` blocks forever waiting to flush it. That hangs the suite
        instead of failing it.
        """
        server_ctx = curvezmq.ServerContext(server_cert_dir)
        client_ctx = curvezmq.ClientContext(client_cert_dir)
        rep = server_ctx.socket(zmq.REP)
        rep.setsockopt(zmq.LINGER, 0)
        port = rep.bind_to_random_port("tcp://127.0.0.1")
        req = client_ctx.socket(zmq.REQ)
        req.setsockopt(zmq.LINGER, 0)
        req.connect(f"tcp://127.0.0.1:{port}")
        try:
            yield rep, req
        finally:
            rep.close(linger=0)
            req.close(linger=0)
            server_ctx.destroy(linger=0)
            client_ctx.destroy(linger=0)

    def test_the_shipped_certificates_complete_a_curvezmq_handshake(
        self, cert_dir, tmp_path
    ):
        """A server on the originals and a client on the copies must talk."""
        worker_dir = self._materialise(
            read_worker_certificates(cert_dir),
            str(tmp_path / "worker" / "certificates"),
        )
        with self._channel(cert_dir, worker_dir) as (rep, req):
            req.send(b"hello from worker")
            assert rep.poll(10_000), "the encrypted handshake never completed"
            assert rep.recv() == b"hello from worker"

    def test_a_worker_with_unrelated_certificates_is_rejected(self, cert_dir, tmp_path):
        """The control for the test above.

        Without this, a regression that disabled encryption entirely would leave
        the handshake test passing -- plaintext sockets connect happily, so the
        assertion above would hold for the wrong reason.
        """
        other = curvezmq.create_certificates(tmp_path / "other")
        bad_dir = self._materialise(
            read_worker_certificates(other), str(tmp_path / "bad" / "certificates")
        )
        with self._channel(cert_dir, bad_dir) as (rep, req):
            req.send(b"should not arrive")
            assert not rep.poll(2_000), (
                "the interchange accepted a client holding the wrong server key, "
                "so the channel is not authenticated"
            )


class TestPublish:
    """Publishing is a SecureString write plus a separate tagging call."""

    def test_the_value_is_a_securestring(self, distributor, cert_dir):
        distributor.publish("job-1", cert_dir)
        assert distributor.ssm.put_parameter.call_args.kwargs["Type"] == "SecureString"

    def test_the_payload_decodes_to_the_certificates(self, distributor, cert_dir):
        distributor.publish("job-1", cert_dir)
        payload = json.loads(distributor.ssm.put_parameter.call_args.kwargs["Value"])
        assert sorted(payload) == sorted(WORKER_CERT_FILES)
        for name in WORKER_CERT_FILES:
            with open(os.path.join(cert_dir, name), "rb") as handle:
                assert base64.b64decode(payload[name]) == handle.read()

    def test_the_name_is_scoped_to_the_provider_and_job(self, distributor, cert_dir):
        name = distributor.publish("job-1", cert_dir)
        assert name == "/parsl-ephemeral/certs/prov1234/job-1"
        assert distributor.ssm.put_parameter.call_args.kwargs["Name"] == name

    def test_it_overwrites(self, distributor, cert_dir):
        """The warm pool reuses an instance, and submits are retried.

        Both mean the same job can publish twice, and the second attempt must
        not fail on ``ParameterAlreadyExists``.
        """
        distributor.publish("job-1", cert_dir)
        assert distributor.ssm.put_parameter.call_args.kwargs["Overwrite"] is True

    def test_tagging_is_a_separate_call(self, distributor, cert_dir):
        """``put_parameter`` rejects ``Tags`` together with ``Overwrite=True``.

        Verified against the live API: "Invalid request: tags and overwrite
        can't be used together." So the tags go through
        ``add_tags_to_resource``.
        """
        distributor.publish("job-1", cert_dir)
        assert "Tags" not in distributor.ssm.put_parameter.call_args.kwargs
        tags = distributor.ssm.add_tags_to_resource.call_args.kwargs["Tags"]
        assert {"Key": "ProviderId", "Value": "prov1234"} in tags

    def test_a_tagging_failure_does_not_fail_the_submit(self, distributor, cert_dir):
        """The parameter is already usable; the tag is only for traceability."""
        distributor.ssm.add_tags_to_resource.side_effect = ClientError(
            {"Error": {"Code": "AccessDeniedException", "Message": "no"}},
            "AddTagsToResource",
        )
        assert distributor.publish("job-1", cert_dir)
        assert distributor.published_parameters == [
            "/parsl-ephemeral/certs/prov1234/job-1"
        ]

    def test_a_put_failure_raises(self, distributor, cert_dir):
        """Unlike tagging: without the parameter the worker cannot start."""
        distributor.ssm.put_parameter.side_effect = ClientError(
            {"Error": {"Code": "AccessDeniedException", "Message": "no"}},
            "PutParameter",
        )
        with pytest.raises(ResourceCreationError, match="Could not publish"):
            distributor.publish("job-1", cert_dir)

    def test_published_parameters_are_tracked_for_cleanup(self, distributor, cert_dir):
        distributor.publish("job-1", cert_dir)
        distributor.publish("job-2", cert_dir)
        assert distributor.published_parameters == [
            "/parsl-ephemeral/certs/prov1234/job-1",
            "/parsl-ephemeral/certs/prov1234/job-2",
        ]

    def test_republishing_the_same_job_does_not_duplicate_the_record(
        self, distributor, cert_dir
    ):
        distributor.publish("job-1", cert_dir)
        distributor.publish("job-1", cert_dir)
        assert len(distributor.published_parameters) == 1


class TestRevoke:
    """Secret key material must not outlive the run that published it."""

    def test_revoke_all_deletes_every_published_parameter(self, distributor, cert_dir):
        distributor.publish("job-1", cert_dir)
        distributor.publish("job-2", cert_dir)
        distributor.revoke_all()
        deleted = {
            call.kwargs["Name"]
            for call in distributor.ssm.delete_parameter.call_args_list
        }
        assert deleted == {
            "/parsl-ephemeral/certs/prov1234/job-1",
            "/parsl-ephemeral/certs/prov1234/job-2",
        }
        assert distributor.published_parameters == []

    def test_revoke_targets_one_job(self, distributor, cert_dir):
        distributor.publish("job-1", cert_dir)
        distributor.publish("job-2", cert_dir)
        distributor.revoke("job-1")
        assert distributor.published_parameters == [
            "/parsl-ephemeral/certs/prov1234/job-2"
        ]

    def test_an_already_deleted_parameter_is_not_an_error(self, distributor, cert_dir):
        """Cleanup is idempotent, and ParameterNotFound means it is already gone."""
        distributor.publish("job-1", cert_dir)
        distributor.ssm.delete_parameter.side_effect = ClientError(
            {"Error": {"Code": "ParameterNotFound", "Message": "gone"}},
            "DeleteParameter",
        )
        distributor.revoke_all()
        assert distributor.published_parameters == []

    def test_a_failed_deletion_warns_and_stops_tracking(
        self, distributor, cert_dir, caplog
    ):
        """It must not raise -- cleanup runs while another error may be in flight.

        But it must be loud: what is left standing is a secret key, so the log
        has to name the parameter for a human to delete.
        """
        distributor.publish("job-1", cert_dir)
        distributor.ssm.delete_parameter.side_effect = ClientError(
            {"Error": {"Code": "AccessDeniedException", "Message": "no"}},
            "DeleteParameter",
        )
        with caplog.at_level("WARNING"):
            distributor.revoke_all()
        assert "/parsl-ephemeral/certs/prov1234/job-1" in caplog.text
        assert "secret key material" in caplog.text

    def test_revoke_all_on_a_fresh_distributor_makes_no_calls(self, distributor):
        distributor.revoke_all()
        distributor.ssm.delete_parameter.assert_not_called()

    def test_adopted_parameters_are_revoked(self, distributor):
        """A resumed provider never published, but still has to clean up.

        Without ``adopt_published`` the certificates from the earlier run stay in
        Parameter Store forever -- the state file is the only record of them.
        """
        distributor.adopt_published(["/parsl-ephemeral/certs/prov1234/old-job"])
        distributor.revoke_all()
        distributor.ssm.delete_parameter.assert_called_once_with(
            Name="/parsl-ephemeral/certs/prov1234/old-job"
        )

    def test_adopting_is_idempotent(self, distributor, cert_dir):
        name = distributor.publish("job-1", cert_dir)
        distributor.adopt_published([name])
        assert distributor.published_parameters == [name]


class TestFetchScript:
    """The worker-side script, which runs unattended in UserData."""

    def test_it_reads_the_job_s_parameter_with_decryption(self, distributor):
        script = distributor.fetch_script("job-1", "/run/certs")
        assert "/parsl-ephemeral/certs/prov1234/job-1" in script
        # Without --with-decryption the value comes back as ciphertext and the
        # JSON parse fails with something unrelated-looking.
        assert "--with-decryption" in script

    def test_it_creates_the_directory_private(self, distributor):
        """``_load_certificate`` raises unless the mode is exactly 0700.

        Created with ``-m`` rather than a later ``chmod`` so there is no window
        at the umask default in which a worker could read and fail.
        """
        script = distributor.fetch_script("job-1", "/run/certs")
        assert f"mkdir -p -m {CERT_DIR_MODE} /run/certs" in script

    def test_it_recreates_the_path_the_command_expects(self, distributor):
        """The command's ``--cert_dir`` is not rewritten, so the path must match."""
        script = distributor.fetch_script("job-1", "/home/ec2-user/x/certificates")
        assert "/home/ec2-user/x/certificates" in script

    def test_it_fails_the_boot_when_the_fetch_fails(self, distributor):
        """Silently continuing produces a worker that dies confusingly later.

        The interesting failure is IAM: without ssm:GetParameter the fetch is
        denied, and an ``exit 1`` here is what makes that visible in the console
        log instead of as a FileNotFoundError from the worker.
        """
        script = distributor.fetch_script("job-1", "/run/certs")
        assert "exit 1" in script
        assert "could not fetch CurveZMQ certificates" in script

    def test_it_removes_the_plaintext_payload(self, distributor):
        """The decrypted JSON must not linger on disk after the fetch."""
        script = distributor.fetch_script("job-1", "/run/certs")
        assert "rm -f /tmp/parsl_certs.json" in script

    def test_it_names_the_session_region(self, distributor):
        """UserData has no region context; the CLI would guess or fail."""
        assert "--region 'us-east-1'" in distributor.fetch_script("job-1", "/run/certs")


class TestCertificateIamStatements:
    """Least-privilege statements for callers supplying their own profile."""

    def test_the_parameter_grant_is_scoped_to_this_provider(self):
        statements = certificate_iam_statements("prov1234")
        resources = statements[0]["Resource"]
        assert resources == [
            "arn:aws:ssm:*:*:parameter/parsl-ephemeral/certs/prov1234/*"
        ]

    def test_only_getparameter_is_granted(self):
        """A worker never writes or deletes; the provider does that."""
        assert certificate_iam_statements("prov1234")[0]["Action"] == [
            "ssm:GetParameter"
        ]

    def test_kms_decrypt_is_constrained_to_ssm(self):
        """SecureString decryption goes through KMS, so the grant is needed.

        Unconstrained it would let a worker decrypt anything in the account that
        uses the SSM key, so it is conditioned on ``kms:ViaService``.
        """
        decrypt = certificate_iam_statements("prov1234")[1]
        assert decrypt["Action"] == ["kms:Decrypt"]
        assert (
            decrypt["Condition"]["StringLike"]["kms:ViaService"]
            == "ssm.*.amazonaws.com"
        )
